#:sdk Microsoft.NET.Sdk
#:property LangVersion=preview

// Post-process Objective Sharpie output for the Maui.RevenueCat.iOS binding.
//
// Applies the deterministic transformations documented in
// src/Maui.RevenueCat.iOS/README.md. Each pass is rule-based with bounded
// scope; anything that needs human judgement (delegate naming, the
// `Name = "..."` symbol-not-found workaround, etc.) is detected and listed
// in a manual-review report instead of edited.
//
// Run as a .NET 10 file-based script:
//     dotnet run .github/scripts/postprocess_ios_bindings.cs -- \
//         ApiDefinitions.cs StructsAndEnums.cs --report manual_review.md

using System.Text;
using System.Text.RegularExpressions;

if (args.Length == 0)
{
    Console.Error.WriteLine(
        "usage: dotnet run postprocess_ios_bindings.cs -- <file>... [--report <path>]");
    return 1;
}

string? reportPath = null;
var files = new List<string>();
for (var i = 0; i < args.Length; i++)
{
    if (args[i] == "--report" && i + 1 < args.Length)
    {
        reportPath = args[++i];
    }
    else
    {
        files.Add(args[i]);
    }
}

var results = new List<FileResult>();
foreach (var file in files)
{
    if (!File.Exists(file))
    {
        Console.Error.WriteLine($"WARN: skipping {file} - not found");
        continue;
    }
    Console.WriteLine($"Processing {file}");
    var r = Postprocess.ProcessFile(file);
    results.Add(r);
    foreach (var (name, delta) in r.PassStats)
    {
        var sign = delta < 0 ? "-" : (delta > 0 ? "+" : ".");
        Console.WriteLine($"   {sign} {name}: {delta:+#;-#;0} chars");
    }
    foreach (var (label, items) in r.Findings)
    {
        Console.WriteLine($"   ! {label}: {items.Count} item(s)");
    }
}

if (reportPath is not null)
{
    Postprocess.WriteReport(results, reportPath);
    Console.WriteLine($"Report written to {reportPath}");
}

return 0;


sealed record FileResult(
    string Path,
    int OriginalChars,
    int FinalChars,
    List<(string Name, int Delta)> PassStats,
    Dictionary<string, List<string>> Findings);


static class Postprocess
{
    // Platform-availability attribute names sharpie emits from clang macros.
    // Stripped wholesale (their presence on Windows hosts causes
    // symbol-not-found warnings and they're encoded for SupportedOSPlatformVersion
    // in the csproj instead).
    private static readonly string[] PlatformAttrNames =
    {
        "iOS", "NoiOS",
        "Mac", "NoMac",
        "MacCatalyst", "NoMacCatalyst",
        "Watch", "NoWatch", "WatchOS", "NoWatchOS",
        "TV", "NoTV", "TvOS", "NoTvOS",
    };

    // Matches a sharpie-style interface block:
    //   optional leading comment line(s)
    //   one or more attribute lines (e.g. [BaseType...], [DisableDefaultCtor], [Category])
    //   interface NAME (: BASE_LIST)?
    //   { ... } with one level of brace nesting allowed inside
    private static readonly Regex InterfaceBlockRe = new(
        @"(?<lead>(?:^[ \t]*//[^\n]*\n)*" +
        @"(?:^[ \t]*\[[^\]]+\][ \t]*\n)+)" +
        @"(?<decl>[ \t]*(?:partial\s+)?interface[ \t]+" +
        @"(?<name>[A-Za-z_]\w*)" +
        @"(?<bases>(?:[ \t]*:[ \t]*[^\n{]+)?)[ \t]*\n)" +
        @"(?<body>[ \t]*\{(?<inner>(?:[^{}]|\{[^{}]*\})*)\}[ \t]*\n?)",
        RegexOptions.Multiline | RegexOptions.Compiled);

    // Symbols the README flags as causing "Undefined symbols for architecture
    // arm64" at link time. Reported, not auto-deleted, because the right
    // action depends on whether the project actually links these symbols.
    private static readonly string[] LinkerRiskSymbols =
    {
        "FakeASIdManager", "FakeAfficheClient", "FakeTrackingManager",
        "NetworkOperation", "PaymentQueueWrapper", "ProductsFetcherSK1",
        "PurchasesReceiptParser", "StoreKit1Wrapper", "StoreKitRequestFetcher",
        "TrackingManagerProxy",
    };

    // Obj-C selectors of NSObject methods bindings inherit and shouldn't
    // re-declare (README).
    private static readonly string[] InheritedNsObjectSelectors =
        { "isEqual:", "description", "debugDescription" };

    // Suffix sharpie applies to category-style Swift extensions of an Obj-C
    // type. Example: `RCAttribution_RevenueCat_Swift_3714` extends `RCAttribution`.
    private static readonly Regex SwiftSuffixRe = new(
        @"^(?<base>.+?)_RevenueCat_Swift_\d+$", RegexOptions.Compiled);

    // ---- transformation passes ----

    // Drop sharpie's [Verify(...)] markers.
    private static string StripVerifyAttributes(string text)
    {
        text = Regex.Replace(text, @"^[ \t]*\[Verify[ \t]*\([^)]*\)\][ \t]*\n", "",
            RegexOptions.Multiline);
        text = Regex.Replace(text, @"\[Verify[ \t]*\([^)]*\)\][ \t]*", "");
        return text;
    }

    // Comment out `(AutoGeneratedName = true)` per README.
    private static string CommentAutoGeneratedName(string text) =>
        Regex.Replace(text, @"\(AutoGeneratedName = true\)",
            "/* (AutoGeneratedName = true) */");

    // Replace `NSUrlRequest` with `NSMutableUrlRequest` (README).
    private static string ReplaceNsUrlRequest(string text) =>
        Regex.Replace(text, @"\bNSUrlRequest\b", "NSMutableUrlRequest");

    // Strip literal `\n` escape sequences inside [Obsoleted("...")] (README).
    private static string StripObsoletedNewlines(string text) =>
        Regex.Replace(text,
            @"\[Obsoleted[ \t]*\(""(?:[^""\\]|\\.)*""\)\]",
            m => m.Value.Replace(@"\n", ""));

    // Drop members marked [Obsoleted(...)] or [Deprecated(...)] (README).
    //
    // Algorithm:
    //   1. Walk line by line; on a marker line, look ahead past following
    //      attribute / comment lines.
    //   2. If the next non-attribute/comment line is an `interface NAME ...`
    //      declaration, this is an INTERFACE-level marker — leave it alone
    //      (RemoveObsoleteInterfaces handles those). Without this guard the
    //      pass would walk forward looking for `;`, miss it (interface body
    //      is `{}`), and consume the next interface's members.
    //   3. Otherwise treat it as a MEMBER marker: rewind over preceding
    //      attribute lines already emitted, then fast-forward to the line
    //      containing `;` outside parentheses. Drop that whole region.
    private static string RemoveObsoleteMembers(string text)
    {
        var lines = text.Split('\n');
        var markerRe = new Regex(@"^[ \t]*\[(?:Obsoleted|Deprecated)[ \t]*\(");
        var attrRe = new Regex(@"^[ \t]*\[[A-Za-z]");
        var interfaceRe = new Regex(@"^[ \t]*(?:partial\s+)?interface[ \t]+");
        var keep = new List<string>(lines.Length);

        for (var i = 0; i < lines.Length; i++)
        {
            if (!markerRe.IsMatch(lines[i]))
            {
                keep.Add(lines[i]);
                continue;
            }

            // (1) Lookahead: skip following attribute / comment lines and see
            // what kind of declaration the marker stack is sitting on.
            var ahead = i + 1;
            while (ahead < lines.Length &&
                   (attrRe.IsMatch(lines[ahead]) ||
                    lines[ahead].TrimStart().StartsWith("//")))
            {
                ahead++;
            }
            if (ahead < lines.Length && interfaceRe.IsMatch(lines[ahead]))
            {
                // (2) Interface-level marker — not this pass's job.
                keep.Add(lines[i]);
                continue;
            }

            // (3) Member-level removal.
            while (keep.Count > 0 && attrRe.IsMatch(keep[^1]))
            {
                keep.RemoveAt(keep.Count - 1);
            }
            var j = i;
            var depth = 0;
            while (j < lines.Length)
            {
                depth += lines[j].Count(c => c == '(') - lines[j].Count(c => c == ')');
                if (depth <= 0 && lines[j].Contains(';')) break;
                j++;
            }
            if (j + 1 < lines.Length && string.IsNullOrWhiteSpace(lines[j + 1]))
            {
                j++;
            }
            i = j;
        }
        return string.Join('\n', keep);
    }

    // Drop entire interface blocks whose lead attributes carry
    // [Obsoleted(...)] or [Deprecated(...)] (README).
    private static string RemoveObsoleteInterfaces(string text)
    {
        var markerRe = new Regex(@"\[(?:Obsoleted|Deprecated)[ \t]*\(");
        var edits = new List<(int Start, int End)>();
        foreach (Match m in InterfaceBlockRe.Matches(text))
        {
            if (markerRe.IsMatch(m.Groups["lead"].Value))
            {
                edits.Add((m.Index, m.Index + m.Length));
            }
        }
        edits.Sort((a, b) => b.Start.CompareTo(a.Start));
        foreach (var (start, end) in edits)
        {
            text = text[..start] + text[end..];
        }
        return text;
    }

    // Drop device-specific availability attributes (README).
    //
    // Targets:
    //   - classic forms: [iOS (X, Y)], [NoiOS], [Mac (...)], [NoMac], ...
    //   - PlatformName-based: [Introduced (PlatformName.iOS, ...)],
    //     [Unavailable (PlatformName.iOS)], [Deprecated (PlatformName.iOS, ...)].
    //
    // Note: this must run AFTER RemoveObsoleteMembers / RemoveObsoleteInterfaces
    // so the obsolete-removal passes still see [Deprecated(PlatformName...)]
    // markers and remove the whole member/interface, not just the attribute.
    private static string StripPlatformAvailabilityAttributes(string text)
    {
        var nameAlt = string.Join("|", PlatformAttrNames.Select(Regex.Escape));

        text = Regex.Replace(
            text,
            $@"^[ \t]*\[(?:{nameAlt})(?:[ \t]*\([^)]*\))?\][ \t]*\n",
            "",
            RegexOptions.Multiline);
        text = Regex.Replace(
            text,
            $@"\[(?:{nameAlt})(?:[ \t]*\([^)]*\))?\][ \t]*",
            "");

        foreach (var attr in new[] { "Introduced", "Unavailable", "Deprecated" })
        {
            text = Regex.Replace(
                text,
                $@"^[ \t]*\[{attr}[ \t]*\([ \t]*PlatformName\.[^)]*\)\][ \t]*\n",
                "",
                RegexOptions.Multiline);
            text = Regex.Replace(
                text,
                $@"\[{attr}[ \t]*\([ \t]*PlatformName\.[^)]*\)\][ \t]*",
                "");
        }
        return text;
    }

    // Drop members whose [Export("...")] selector matches isEqual: / description
    // / debugDescription -- inherited from NSObject (README).
    private static string RemoveInheritedNsObjectMethods(string text)
    {
        var selAlt = string.Join("|", InheritedNsObjectSelectors.Select(Regex.Escape));
        var targetRe = new Regex(
            $@"^[ \t]*\[[ \t]*Export[ \t]*\([ \t]*""(?:{selAlt})""[ \t]*\)\]");
        var attrRe = new Regex(@"^[ \t]*\[[A-Za-z]");

        var lines = text.Split('\n');
        var keep = new List<string>(lines.Length);
        for (var i = 0; i < lines.Length; i++)
        {
            if (targetRe.IsMatch(lines[i]))
            {
                while (keep.Count > 0 && attrRe.IsMatch(keep[^1]))
                {
                    keep.RemoveAt(keep.Count - 1);
                }
                var j = i;
                while (j < lines.Length && !lines[j].Contains(';')) j++;
                if (j + 1 < lines.Length && string.IsNullOrWhiteSpace(lines[j + 1])) j++;
                i = j;
                continue;
            }
            keep.Add(lines[i]);
        }
        return string.Join('\n', keep);
    }

    // Fold XXX_RevenueCat_Swift_NNNN interfaces into the canonical XXX
    // interface (README, e.g. `RCAttribution_RevenueCat_Swift_3714`).
    //
    // Canonical's attributes/base list are preserved; only the suffix
    // interface's *members* are appended. The suffix block (lead attributes
    // + body) is removed in full.
    private static string MergeSwiftSuffixInterfaces(string text)
    {
        var byName = new Dictionary<string, Match>();
        foreach (Match m in InterfaceBlockRe.Matches(text))
        {
            byName[m.Groups["name"].Value] = m;
        }

        var edits = new List<(int Start, int End, string Replacement)>();
        foreach (var (name, m) in byName)
        {
            var sm = SwiftSuffixRe.Match(name);
            if (!sm.Success) continue;
            if (!byName.TryGetValue(sm.Groups["base"].Value, out var canonical)) continue;

            var suffixInner = m.Groups["inner"].Value;
            if (string.IsNullOrWhiteSpace(suffixInner))
            {
                edits.Add((m.Index, m.Index + m.Length, ""));
                continue;
            }

            var canonicalInner = canonical.Groups["inner"].Value.TrimEnd();
            var newInner = canonicalInner + "\n\n" + suffixInner.Trim('\n') + "\n";
            var newBody = "{" + newInner + "}";

            var origBody = canonical.Groups["body"].Value;
            var trailing = origBody[origBody.TrimEnd().Length..];
            var newCanonical =
                canonical.Groups["lead"].Value +
                canonical.Groups["decl"].Value +
                newBody +
                trailing;

            edits.Add((canonical.Index, canonical.Index + canonical.Length, newCanonical));
            edits.Add((m.Index, m.Index + m.Length, ""));
        }

        if (edits.Count == 0) return text;
        edits.Sort((a, b) => b.Start.CompareTo(a.Start));
        foreach (var (start, end, replacement) in edits)
        {
            text = text[..start] + replacement + text[end..];
        }
        return text;
    }

    // Drop interface blocks whose bodies contain no real members after the
    // earlier passes (README). Iterates to a fixed point.
    private static string RemoveEmptyInterfaces(string text)
    {
        while (true)
        {
            var edits = new List<(int Start, int End)>();
            foreach (Match m in InterfaceBlockRe.Matches(text))
            {
                var inner = m.Groups["inner"].Value;
                var noBlock = Regex.Replace(inner, @"/\*.*?\*/", "", RegexOptions.Singleline);
                var noLine = Regex.Replace(noBlock, @"//[^\n]*", "");
                if (string.IsNullOrWhiteSpace(noLine))
                {
                    edits.Add((m.Index, m.Index + m.Length));
                }
            }
            if (edits.Count == 0) return text;
            edits.Sort((a, b) => b.Start.CompareTo(a.Start));
            foreach (var (start, end) in edits)
            {
                text = text[..start] + text[end..];
            }
        }
    }

    // Add INativeObject to every interface used as the TValue of an
    // NSDictionary<TKey, TValue> (README).
    //
    // NSDictionary<TKey, TValue> constrains TValue : INativeObject. Without
    // the marker the build fails with
    //   "cannot be used as type parameter 'TValue' in the generic type or
    //    method 'NSDictionary<TKey, TValue>'".
    private static string AddInativeObjectForDictValues(string text)
    {
        var valueTypes = new HashSet<string>();
        var dictRe = new Regex(
            @"NSDictionary[ \t]*<[ \t]*[A-Za-z_]\w*[ \t]*,[ \t]*([A-Za-z_]\w*)[ \t]*>");
        foreach (Match m in dictRe.Matches(text))
        {
            valueTypes.Add(m.Groups[1].Value);
        }
        if (valueTypes.Count == 0) return text;

        return InterfaceBlockRe.Replace(text, m =>
        {
            var name = m.Groups["name"].Value;
            if (!valueTypes.Contains(name)) return m.Value;
            var bases = m.Groups["bases"].Value;
            if (bases.Contains("INativeObject")) return m.Value;

            var newBases = bases.TrimStart().StartsWith(':')
                ? bases.TrimEnd() + ", INativeObject"
                : " : INativeObject";

            var declWithBases = Regex.Replace(
                m.Groups["decl"].Value,
                @"interface[ \t]+" + Regex.Escape(name) + @"(?:[ \t]*:[ \t]*[^\n{]+)?",
                $"interface {name}{newBases}");

            return m.Groups["lead"].Value + declWithBases + m.Groups["body"].Value;
        });
    }

    // Drop top-level `delegate <ret> <Name>(...);` declarations whose name
    // has no other reference in the file (README -- "removed delegate that
    // was not used anywhere").
    private static string RemoveUnusedDelegates(string text)
    {
        var declRe = new Regex(
            @"^delegate[ \t]+[^\n;]+?[ \t](?<name>[A-Za-z_]\w*)[ \t]*\([^;]*\);[ \t]*\n",
            RegexOptions.Multiline);

        var matches = declRe.Matches(text).Cast<Match>().ToList();
        if (matches.Count == 0) return text;

        var edits = new List<(int Start, int End)>();
        foreach (var m in matches)
        {
            var name = m.Groups["name"].Value;
            var refCount = Regex.Matches(text, $@"\b{Regex.Escape(name)}\b").Count;
            if (refCount <= 1)
            {
                edits.Add((m.Index, m.Index + m.Length));
            }
        }
        edits.Sort((a, b) => b.Start.CompareTo(a.Start));
        foreach (var (start, end) in edits)
        {
            text = text[..start] + text[end..];
        }
        return text;
    }

    // ---- detection-only passes ----

    private static List<string> DetectBlockCallbackActions(string text)
    {
        var pattern = new Regex(
            @"\[BlockCallback\][ \t]*(?<kind>Action|Func)<(?<args>[^>]+)>" +
            @"[ \t]+(?<param>[A-Za-z_]\w*)");
        var hits = new List<string>();
        foreach (Match m in pattern.Matches(text))
        {
            hits.Add(
                $"`[BlockCallback] {m.Groups["kind"].Value}<{m.Groups["args"].Value.Trim()}> " +
                $"{m.Groups["param"].Value}` - extract to a named delegate");
        }
        return hits;
    }

    private static List<string> DetectLinkerRiskSymbols(string text)
    {
        var hits = new List<string>();
        foreach (var sym in LinkerRiskSymbols)
        {
            if (Regex.IsMatch(text, $@"\b{Regex.Escape(sym)}\b"))
            {
                hits.Add($"`{sym}` declared - delete from ApiDefinitions.cs if linker reports it as undefined");
            }
        }
        return hits;
    }

    private static List<string> DetectRemainingVerify(string text) =>
        Regex.IsMatch(text, @"\[Verify[ \t]*\(")
            ? new List<string> { "At least one `[Verify(...)]` attribute survived stripping - inspect." }
            : new List<string>();

    private static List<string> DetectNameAttributes(string text)
    {
        var count = Regex.Matches(text, @"Name[ \t]*=[ \t]*""[^""]+""").Count;
        if (count == 0) return new List<string>();
        return new List<string>
        {
            $"{count} `Name = \"...\"` attribute argument(s) present - " +
            "if Windows build emits symbol-not-found errors, the README's fix is to drop these.",
        };
    }

    // ---- driver ----

    // Order matters:
    //   1. Strip Verify before anything else looks at attribute structure.
    //   2. Run obsolete/deprecated member+interface removal BEFORE stripping
    //      [Deprecated (PlatformName...)] as a platform attr, otherwise the
    //      marker would be gone by the time the member-removal pass ran.
    //   3. Strip remaining platform attrs.
    //   4. Merge swift-suffix interfaces, then prune any interfaces left empty.
    //   5. Cross-reference passes (INativeObject, unused delegates) last.
    private static readonly (string Name, Func<string, string> Fn)[] Passes =
    {
        ("strip [Verify(...)]",                       StripVerifyAttributes),
        ("comment (AutoGeneratedName = true)",        CommentAutoGeneratedName),
        ("NSUrlRequest -> NSMutableUrlRequest",       ReplaceNsUrlRequest),
        ("strip \\n in [Obsoleted(...)]",             StripObsoletedNewlines),
        ("remove [Obsoleted/Deprecated] members",     RemoveObsoleteMembers),
        ("remove [Obsoleted/Deprecated] interfaces",  RemoveObsoleteInterfaces),
        ("strip device-specific availability attrs",  StripPlatformAvailabilityAttributes),
        ("remove inherited NSObject methods",         RemoveInheritedNsObjectMethods),
        ("merge _RevenueCat_Swift_NNNN interfaces",   MergeSwiftSuffixInterfaces),
        ("remove empty interfaces",                   RemoveEmptyInterfaces),
        ("add INativeObject for NSDictionary values", AddInativeObjectForDictValues),
        ("remove unused top-level delegates",         RemoveUnusedDelegates),
    };

    private static readonly (string Label, Func<string, List<string>> Fn)[] Detectors =
    {
        ("Inline `[BlockCallback] Action<>` / `Func<>` parameters", DetectBlockCallbackActions),
        ("Linker-risk symbols (per README troubleshooting)",        DetectLinkerRiskSymbols),
        ("Surviving `[Verify]` attributes",                         DetectRemainingVerify),
        ("`Name = \"...\"` attribute arguments",                    DetectNameAttributes),
    };

    public static FileResult ProcessFile(string path)
    {
        var original = File.ReadAllText(path);
        // Normalize CRLF -> LF for regex compatibility; restore on write so
        // we don't churn line endings. sharpie itself emits LF on macOS, but
        // local testing on Windows can hit CRLF.
        var hadCrLf = original.Contains("\r\n");
        var text = hadCrLf ? original.Replace("\r\n", "\n") : original;
        var stats = new List<(string Name, int Delta)>();
        foreach (var (name, fn) in Passes)
        {
            var before = text.Length;
            text = fn(text);
            stats.Add((name, text.Length - before));
        }
        var output = hadCrLf ? text.Replace("\n", "\r\n") : text;
        File.WriteAllText(path, output);

        var findings = new Dictionary<string, List<string>>();
        foreach (var (label, fn) in Detectors)
        {
            var items = fn(text);
            if (items.Count > 0) findings[label] = items;
        }
        return new FileResult(path, original.Length, text.Length, stats, findings);
    }

    public static void WriteReport(List<FileResult> results, string reportPath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# iOS Bindings Post-Processing Report");
        sb.AppendLine();
        sb.AppendLine("Automated cleanups have been applied. The items below still need a human");
        sb.AppendLine("eye before the binding will compile cleanly.");
        sb.AppendLine();

        foreach (var r in results)
        {
            sb.AppendLine($"## `{System.IO.Path.GetFileName(r.Path)}`");
            sb.AppendLine();
            var delta = r.FinalChars - r.OriginalChars;
            sb.AppendLine($"- Original size: {r.OriginalChars} chars");
            sb.AppendLine($"- Final size:    {r.FinalChars} chars ({delta:+#;-#;0})");
            sb.AppendLine();
            sb.AppendLine("### Pass results");
            sb.AppendLine();
            sb.AppendLine("| Pass | Delta chars |");
            sb.AppendLine("|------|------------:|");
            foreach (var (name, d) in r.PassStats)
            {
                sb.AppendLine($"| {name} | {d:+#;-#;0} |");
            }
            sb.AppendLine();

            if (r.Findings.Count > 0)
            {
                sb.AppendLine("### Manual follow-ups detected");
                sb.AppendLine();
                foreach (var (label, items) in r.Findings)
                {
                    sb.AppendLine($"**{label}**");
                    sb.AppendLine();
                    foreach (var item in items)
                    {
                        sb.AppendLine($"- {item}");
                    }
                    sb.AppendLine();
                }
            }
            else
            {
                sb.AppendLine("_No issues detected by the static checks. Still skim the diff before merging._");
                sb.AppendLine();
            }
        }

        File.WriteAllText(reportPath, sb.ToString());
    }
}
