using Xunit;

namespace Postprocess.Tests;

/// <summary>
/// End-to-end fixture tests for the post-processor script.
///
/// Each test feeds a self-contained fixture through the script (via
/// <see cref="ScriptRunner"/>) and asserts on the rewritten output. Because
/// each test pays a `dotnet run` cold start, fixtures are kept small and
/// focused; one fixture per behavioral concern rather than long shared inputs.
/// </summary>
public class PassTests
{
    // ──────────────────────── Verify ─────────────────────────────────────

    [Fact]
    public void StripVerify_RemovesStandaloneAttribute()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Verify (MethodToProperty)]
                    [Export ("bar")]
                    void Bar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("[Verify", output);
        Assert.Contains("[Export (\"bar\")]", output);
        Assert.Contains("void Bar ();", output);
    }

    [Fact]
    public void StripVerify_RemovesInlineAttribute()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Verify (MethodToProperty)] [Export ("bar")]
                    void Bar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("[Verify", output);
        Assert.Contains("[Export (\"bar\")]", output);
    }

    // ──────────────────────── (AutoGeneratedName = true) ─────────────────

    [Fact]
    public void AutoGeneratedName_IsCommentedOut()
    {
        const string input = """
            namespace T
            {
                [Category (AutoGeneratedName = true)]
                [BaseType (typeof(RCFoo))]
                interface RCFoo_Bar { }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.Contains("/* (AutoGeneratedName = true) */", output);
        Assert.DoesNotMatch(@"\(AutoGeneratedName = true\)(?!\s*\*/)", output);
    }

    // ──────────────────────── NSUrlRequest → NSMutableUrlRequest ─────────

    [Fact]
    public void NSUrlRequest_IsReplacedWithMutableVariant()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("foo:")]
                    void Foo (NSUrlRequest request);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("NSUrlRequest ", output);
        Assert.Contains("NSMutableUrlRequest", output);
    }

    [Fact]
    public void NSMutableUrlRequest_IsLeftAlone()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("foo:")]
                    void Foo (NSMutableUrlRequest request);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        // Only one occurrence — we did not double-replace.
        var count = Substrings.Count(output, "NSMutableUrlRequest");
        Assert.Equal(1, count);
    }

    // ──────────────────────── [Obsoleted] / [Deprecated] members ─────────

    [Fact]
    public void ObsoletedMember_IsRemovedAlongWithItsAttributeStack()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Obsoleted (PlatformName.iOS, 1, 0, message: "renamed")]
                    [Export ("oldBar:")]
                    void OldBar (NSString s);

                    [Export ("newBar")]
                    void NewBar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("OldBar", output);
        Assert.DoesNotContain("oldBar:", output);
        Assert.DoesNotContain("[Obsoleted", output);
        Assert.Contains("NewBar", output);
    }

    [Fact]
    public void DeprecatedMember_IsRemoved()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Deprecated (PlatformName.iOS, 0, 0, 1, message: "use newer API")]
                    [Export ("oldBar")]
                    void OldBar ();

                    [Export ("newBar")]
                    void NewBar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("OldBar", output);
        Assert.Contains("NewBar", output);
    }

    // ──────────────────────── [Obsoleted] / [Deprecated] interfaces ──────

    [Fact]
    public void ObsoletedInterface_IsRemovedEntirely()
    {
        const string input = """
            namespace T
            {
                // @interface RCOldThing : NSObject
                [Obsoleted (PlatformName.iOS, 1, 0, message: "renamed to RCNewThing")]
                [BaseType (typeof(NSObject))]
                interface RCOldThing
                {
                }

                [BaseType (typeof(NSObject))]
                interface RCNewThing
                {
                    [Export ("foo")]
                    void Foo ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("RCOldThing", output);
        Assert.Contains("RCNewThing", output);
    }

    /// <summary>
    /// Regression for the bug where an interface-level [Obsoleted] marker on
    /// an empty interface caused the member-removal pass to walk forward past
    /// the empty body looking for `;` and eat the next interface's members.
    /// </summary>
    [Fact]
    public void Regression_EmptyObsoleteInterface_DoesNotEatNextInterface()
    {
        const string input = """
            namespace T
            {
                [Obsoleted (PlatformName.iOS, 1, 0, message: "x")]
                [BaseType (typeof(NSObject))]
                interface RCOldEmpty
                {
                }

                [BaseType (typeof(NSObject))]
                interface RCNext
                {
                    [Export ("alive")]
                    string Alive { get; }

                    [Export ("alsoAlive")]
                    string AlsoAlive { get; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("RCOldEmpty", output);
        Assert.Contains("string Alive { get; }", output);
        Assert.Contains("string AlsoAlive { get; }", output);
    }

    // ──────────────────────── Device-specific availability attrs ─────────

    [Fact]
    public void PlatformAvailabilityAttrs_AreStripped()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Unavailable (PlatformName.WatchOS)]
                    [Introduced (PlatformName.iOS, 13, 0)]
                    [Export ("foo")]
                    void Foo ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("[Unavailable", output);
        Assert.DoesNotContain("[Introduced", output);
        Assert.Contains("void Foo", output);
    }

    // ──────────────────────── Inherited NSObject methods ─────────────────

    [Fact]
    public void InheritedNSObjectMethods_AreRemoved()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("isEqual:")]
                    bool IsEqual ([NullAllowed] NSObject other);

                    [Export ("description")]
                    string Description { get; }

                    [Export ("debugDescription")]
                    string DebugDescription { get; }

                    [Export ("balance")]
                    nint Balance { get; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("IsEqual", output);
        Assert.DoesNotContain("DebugDescription", output);
        // `description` should be gone; `Description` shouldn't appear as a property name.
        Assert.DoesNotContain("string Description", output);
        Assert.Contains("nint Balance { get; }", output);
    }

    // ──────────────────────── _Swift_NNNN merging ────────────────────────

    [Fact]
    public void Merge_SingleSuffixIntoCanonical()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCAttribution
                {
                    [Export ("enable")]
                    void Enable ();
                }

                [Category]
                [BaseType (typeof(RCAttribution))]
                interface RCAttribution_RevenueCat_Swift_3714
                {
                    [Export ("collect")]
                    void Collect ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("_RevenueCat_Swift_3714", output);
        // Canonical should contain BOTH members.
        var canonicalBody = ExtractInterfaceBody(output, "RCAttribution");
        Assert.NotNull(canonicalBody);
        Assert.Contains("void Enable ()", canonicalBody);
        Assert.Contains("void Collect ()", canonicalBody);
    }

    /// <summary>
    /// Regression for the bug where two suffix interfaces targeting the same
    /// canonical caused the merge pass to issue two overlapping replace edits
    /// at the same offset. Applying them in sequence sliced into already-modified
    /// text, dropping members and corrupting comment prefixes (e.g. `//` → `/`).
    /// </summary>
    [Fact]
    public void Regression_Merge_MultipleSuffixesIntoSameCanonical()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCAttribution
                {
                    [Export ("enable")]
                    void Enable ();
                }

                [Category]
                [BaseType (typeof(RCAttribution))]
                interface RCAttribution_RevenueCat_Swift_3714
                {
                    // -(void)collect;
                    [Export ("collect")]
                    void Collect ();
                }

                [Category]
                [BaseType (typeof(RCAttribution))]
                interface RCAttribution_RevenueCat_Swift_4901
                {
                    // -(void)setEmail:(NSString *)email;
                    [Export ("setEmail:")]
                    void SetEmail (string email);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("_RevenueCat_Swift_", output);

        var body = ExtractInterfaceBody(output, "RCAttribution");
        Assert.NotNull(body);
        Assert.Contains("void Enable ()", body);
        Assert.Contains("void Collect ()", body);
        Assert.Contains("void SetEmail (string email)", body);

        // No `//` should have been mangled to `/` (regression).
        Assert.DoesNotMatch(@"^\s*/ -\(", output.ReplaceLineEndings("\n"));
    }

    /// <summary>
    /// Regression for the bug where merging dropped the leading whitespace
    /// before `{` and `}`, leaving braces at column 0 instead of the canonical's
    /// original indent.
    /// </summary>
    [Fact]
    public void Regression_Merge_PreservesBraceIndentation()
    {
        const string input = """
            namespace T
            {
            	[BaseType (typeof(NSObject))]
            	interface RCAttribution
            	{
            		[Export ("enable")]
            		void Enable ();
            	}

            	[Category]
            	[BaseType (typeof(RCAttribution))]
            	interface RCAttribution_RevenueCat_Swift_3714
            	{
            		[Export ("collect")]
            		void Collect ();
            	}
            }
            """;
        var output = ScriptRunner.Run(input);

        // The canonical's `{` and `}` should remain tab-indented (one tab,
        // matching the input), NOT slammed against column 0.
        Assert.Matches(@"interface RCAttribution\s*\r?\n\t\{", output);
        Assert.Matches(@"\r?\n\t\}", output);
    }

    // ──────────────────────── Empty-interface removal ────────────────────

    [Fact]
    public void EmptyInterface_IsRemoved()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCEmpty
                {
                }

                [BaseType (typeof(NSObject))]
                interface RCNonEmpty
                {
                    [Export ("foo")]
                    void Foo ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("RCEmpty", output);
        Assert.Contains("RCNonEmpty", output);
    }

    // ──────────────────────── INativeObject for NSDictionary values ──────

    [Fact]
    public void DictionaryValueType_GainsINativeObject()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCValue
                {
                    [Export ("foo")]
                    string Foo { get; }
                }

                [BaseType (typeof(NSObject))]
                interface RCHolder
                {
                    [Export ("all", ArgumentSemantic.Copy)]
                    NSDictionary<NSString, RCValue> All { get; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.Matches(@"interface RCValue[^\n{]*:\s*INativeObject", output);
    }

    [Fact]
    public void DictionaryValueType_DoesNotDoubleAddINativeObject()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCValue : INativeObject
                {
                    [Export ("foo")]
                    string Foo { get; }
                }

                [BaseType (typeof(NSObject))]
                interface RCHolder
                {
                    [Export ("all", ArgumentSemantic.Copy)]
                    NSDictionary<NSString, RCValue> All { get; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        // Should still inherit once, not "INativeObject, INativeObject".
        var count = Substrings.Count(output, "INativeObject");
        Assert.Equal(1, count);
    }

    // ──────────────────────── Unused delegate removal ────────────────────

    [Fact]
    public void UnusedTopLevelDelegate_IsRemoved()
    {
        const string input = """
            namespace T
            {
                delegate void UnusedHandler (NSError error);
                delegate void UsedHandler (NSError error);

                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("doWith:")]
                    void DoWith ([BlockCallback] UsedHandler completion);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("UnusedHandler", output);
        Assert.Contains("UsedHandler", output);
    }

    // ──────────────────────── Idempotency ────────────────────────────────

    [Fact]
    public void Script_IsIdempotent()
    {
        const string input = """
            namespace T
            {
                [Obsoleted (PlatformName.iOS, 1, 0, message: "renamed")]
                [BaseType (typeof(NSObject))]
                interface RCOld
                {
                }

                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Verify (MethodToProperty)]
                    [Obsoleted (PlatformName.iOS, 1, 0, message: "renamed")]
                    [Export ("oldBar")]
                    void OldBar ();

                    [Export ("newBar")]
                    void NewBar ();
                }
            }
            """;
        var once = ScriptRunner.Run(input);
        var twice = ScriptRunner.Run(once);
        Assert.Equal(once, twice);
    }

    // ──────────────────────── helpers ────────────────────────────────────

    /// <summary>
    /// Returns the inner body text of <c>interface NAME { ... }</c> in <paramref name="source"/>,
    /// or null if not found. Brace nesting one level deep is supported (for property
    /// accessor lists like <c>{ get; }</c>).
    /// </summary>
    private static string? ExtractInterfaceBody(string source, string name)
    {
        var marker = $"interface {name}";
        var idx = source.IndexOf(marker);
        if (idx < 0) return null;
        var brace = source.IndexOf('{', idx + marker.Length);
        if (brace < 0) return null;

        var depth = 1;
        for (var i = brace + 1; i < source.Length; i++)
        {
            if (source[i] == '{') depth++;
            else if (source[i] == '}')
            {
                depth--;
                if (depth == 0) return source[(brace + 1)..i];
            }
        }
        return null;
    }
}

internal static class Substrings
{
    public static int Count(string haystack, string needle)
    {
        if (needle.Length == 0) return 0;
        var count = 0;
        var i = 0;
        while ((i = haystack.IndexOf(needle, i, StringComparison.Ordinal)) >= 0)
        {
            count++;
            i += needle.Length;
        }
        return count;
    }
}
