using Xunit;

namespace Postprocess.Tests;

/// <summary>
/// End-to-end fixture tests for the post-processor script.
///
/// Each test feeds a self-contained fixture through the script (via
/// <see cref="ScriptRunner"/>) and asserts on the rewritten output. Because
/// each test pays a `dotnet run` cold start, fixtures are kept small and
/// focused; one fixture per behavioral concern rather than long shared inputs.
/// </summary>
public class PassTests
{
    // ──────────────────────── Verify ─────────────────────────────────────

    [Fact]
    public void StripVerify_RemovesStandaloneAttribute()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Verify (MethodToProperty)]
                    [Export ("bar")]
                    void Bar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("[Verify", output);
        Assert.Contains("[Export (\"bar\")]", output);
        Assert.Contains("void Bar ();", output);
    }

    [Fact]
    public void StripVerify_RemovesInlineAttribute()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Verify (MethodToProperty)] [Export ("bar")]
                    void Bar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("[Verify", output);
        Assert.Contains("[Export (\"bar\")]", output);
    }

    // ──────────────────────── Multi-line // doc comments ─────────────────

    /// <summary>
    /// Regression for sharpie emitting `// @property ... deprecated("` with the
    /// deprecation message spanning multiple physical newlines. Only the first
    /// line has `//`, so subsequent lines parse as C# code and break the build.
    /// </summary>
    [Fact]
    public void Regression_MultilineDocComment_IsCollapsedOntoOneLine()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    // @property (nonatomic) BOOL allowSharing __attribute__((deprecated("
                        Configure behavior through the dashboard instead. If you have configured the "Legacy"
                        restore behavior, keep this active.
                        ")));
                    [Export ("allowSharing")]
                    bool AllowSharing { get; set; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        // The collapsed comment line should now contain the entire deprecation
        // message on a single line, and no orphan continuation lines should remain.
        Assert.DoesNotMatch(@"^[ \t]+Configure behavior", output);
        Assert.DoesNotMatch(@"^[ \t]+restore behavior", output);
        Assert.DoesNotMatch(@"^[ \t]+""\)\)\);", output);
        // The property declaration should be intact.
        Assert.Contains("bool AllowSharing { get; set; }", output);
    }

    // ──────────────────────── (AutoGeneratedName = true) ─────────────────

    [Fact]
    public void AutoGeneratedName_IsCommentedOut()
    {
        const string input = """
            namespace T
            {
                [Category (AutoGeneratedName = true)]
                [BaseType (typeof(RCFoo))]
                interface RCFoo_Bar { }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.Contains("/* (AutoGeneratedName = true) */", output);
        Assert.DoesNotMatch(@"\(AutoGeneratedName = true\)(?!\s*\*/)", output);
    }

    // ──────────────────────── NSUrlRequest → NSMutableUrlRequest ─────────

    [Fact]
    public void NSUrlRequest_IsReplacedWithMutableVariant()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("foo:")]
                    void Foo (NSUrlRequest request);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("NSUrlRequest ", output);
        Assert.Contains("NSMutableUrlRequest", output);
    }

    [Fact]
    public void NSMutableUrlRequest_IsLeftAlone()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("foo:")]
                    void Foo (NSMutableUrlRequest request);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        // Only one occurrence — we did not double-replace.
        var count = Substrings.Count(output, "NSMutableUrlRequest");
        Assert.Equal(1, count);
    }

    // ──────────────────────── Cocoa-acronym casing ───────────────────────

    [Fact]
    public void CocoaAcronyms_AreNormalizedToPascalCase()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("foo:")]
                    void Foo (NSURL url, NSUUID uuid, NSHTTPURLResponse response);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.Contains("NSUrl ", output);
        Assert.Contains("NSUuid ", output);
        Assert.Contains("NSHttpUrlResponse", output);
        Assert.DoesNotContain("NSURL ", output);
        Assert.DoesNotContain("NSUUID", output);
        Assert.DoesNotContain("NSHTTPURLResponse", output);
    }

    // ──────────────────────── [Obsoleted] / [Deprecated] members ─────────

    [Fact]
    public void ObsoletedMember_IsRemovedAlongWithItsAttributeStack()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Obsoleted (PlatformName.iOS, 1, 0, message: "renamed")]
                    [Export ("oldBar:")]
                    void OldBar (NSString s);

                    [Export ("newBar")]
                    void NewBar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("OldBar", output);
        Assert.DoesNotContain("oldBar:", output);
        Assert.DoesNotContain("[Obsoleted", output);
        Assert.Contains("NewBar", output);
    }

    [Fact]
    public void DeprecatedMember_IsRemoved()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Deprecated (PlatformName.iOS, 0, 0, 1, message: "use newer API")]
                    [Export ("oldBar")]
                    void OldBar ();

                    [Export ("newBar")]
                    void NewBar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("OldBar", output);
        Assert.Contains("NewBar", output);
    }

    // ──────────────────────── [Obsoleted] / [Deprecated] interfaces ──────

    [Fact]
    public void ObsoletedInterface_IsRemovedEntirely()
    {
        const string input = """
            namespace T
            {
                // @interface RCOldThing : NSObject
                [Obsoleted (PlatformName.iOS, 1, 0, message: "renamed to RCNewThing")]
                [BaseType (typeof(NSObject))]
                interface RCOldThing
                {
                }

                [BaseType (typeof(NSObject))]
                interface RCNewThing
                {
                    [Export ("foo")]
                    void Foo ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("RCOldThing", output);
        Assert.Contains("RCNewThing", output);
    }

    /// <summary>
    /// Regression for the bug where an interface-level [Obsoleted] marker on
    /// an empty interface caused the member-removal pass to walk forward past
    /// the empty body looking for `;` and eat the next interface's members.
    /// </summary>
    [Fact]
    public void Regression_EmptyObsoleteInterface_DoesNotEatNextInterface()
    {
        const string input = """
            namespace T
            {
                [Obsoleted (PlatformName.iOS, 1, 0, message: "x")]
                [BaseType (typeof(NSObject))]
                interface RCOldEmpty
                {
                }

                [BaseType (typeof(NSObject))]
                interface RCNext
                {
                    [Export ("alive")]
                    string Alive { get; }

                    [Export ("alsoAlive")]
                    string AlsoAlive { get; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("RCOldEmpty", output);
        Assert.Contains("string Alive { get; }", output);
        Assert.Contains("string AlsoAlive { get; }", output);
    }

    // ──────────────────────── Linker-risk symbol removal ─────────────────

    [Fact]
    public void LinkerRiskInterface_IsRemovedEntirely()
    {
        const string input = """
            namespace T
            {
                // @interface PaymentQueueWrapper : NSObject
                [BaseType (typeof(NSObject))]
                interface PaymentQueueWrapper
                {
                    [Export ("foo")]
                    void Foo ();
                }

                [BaseType (typeof(NSObject))]
                interface RCKept
                {
                    [Export ("bar")]
                    void Bar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("PaymentQueueWrapper", output);
        Assert.Contains("interface RCKept", output);
        Assert.Contains("void Bar ();", output);
    }

    /// <summary>
    /// Regression: sharpie binds Swift extensions of the internal linker-risk
    /// types as <c>[Category] [BaseType (typeof(X))]</c> interfaces. Dropping
    /// the X interface but leaving the category produces a dangling
    /// <c>typeof(X)</c> (CS0246) — and the category body can itself reference X
    /// (e.g. a static <c>default</c> accessor). The whole dependent category
    /// must be removed alongside its base.
    /// </summary>
    [Fact]
    public void Regression_LinkerRiskCategory_DependentExtensionIsRemoved()
    {
        const string input = """
            namespace T
            {
                // @interface PurchasesReceiptParser : NSObject
                [BaseType (typeof(NSObject))]
                interface PurchasesReceiptParser
                {
                    [Export ("receiptHasTransactionsWithReceiptData:")]
                    bool ReceiptHasTransactions (NSData receiptData);
                }

                // @interface RevenueCat_Swift_3922 (PurchasesReceiptParser)
                [Category]
                [BaseType (typeof(PurchasesReceiptParser))]
                interface PurchasesReceiptParser_RevenueCat_Swift_3922
                {
                    [Static]
                    [Export ("default_", ArgumentSemantic.Strong)]
                    PurchasesReceiptParser Default_ { [Bind ("default")] get; }
                }

                [BaseType (typeof(NSObject))]
                interface RCKept
                {
                    [Export ("foo")]
                    void Foo ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("PurchasesReceiptParser", output);
        Assert.Contains("interface RCKept", output);
        Assert.Contains("void Foo ();", output);
    }

    // ──────────────────────── Device-specific availability attrs ─────────

    /// <summary>
    /// Regression for the bug where sharpie emits multiple platform attributes
    /// on a single line as `[Watch (...), TV (...), Mac (...), iOS (...)]` and
    /// the strip pass only matched single-entry lines, leaving these intact.
    /// bgen on recent .NET-for-iOS then errors out because
    /// `MacAttribute`/`WatchAttribute` aren't in the net9.0-ios targeting pack.
    /// </summary>
    [Fact]
    public void Regression_CombinedPlatformAttrsLine_IsStripped()
    {
        const string input = """
            namespace T
            {
                [Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("bar")]
                    void Bar ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("Watch (", output);
        Assert.DoesNotContain("Mac (",   output);
        Assert.DoesNotContain("TV (",    output);
        Assert.DoesNotContain("iOS (",   output);
        Assert.Contains("interface RCFoo", output);
    }

    [Fact]
    public void PlatformAvailabilityAttrs_AreStripped()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Unavailable (PlatformName.WatchOS)]
                    [Introduced (PlatformName.iOS, 13, 0)]
                    [Export ("foo")]
                    void Foo ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("[Unavailable", output);
        Assert.DoesNotContain("[Introduced", output);
        Assert.Contains("void Foo", output);
    }

    // ──────────────────────── Inherited NSObject methods ─────────────────

    [Fact]
    public void InheritedNSObjectMethods_AreRemoved()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("isEqual:")]
                    bool IsEqual ([NullAllowed] NSObject other);

                    [Export ("description")]
                    string Description { get; }

                    [Export ("debugDescription")]
                    string DebugDescription { get; }

                    [Export ("balance")]
                    nint Balance { get; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("IsEqual", output);
        Assert.DoesNotContain("DebugDescription", output);
        // `description` should be gone; `Description` shouldn't appear as a property name.
        Assert.DoesNotContain("string Description", output);
        Assert.Contains("nint Balance { get; }", output);
    }

    // ──────────────────────── _Swift_NNNN merging ────────────────────────

    [Fact]
    public void Merge_SingleSuffixIntoCanonical()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCAttribution
                {
                    [Export ("enable")]
                    void Enable ();
                }

                [Category]
                [BaseType (typeof(RCAttribution))]
                interface RCAttribution_RevenueCat_Swift_3714
                {
                    [Export ("collect")]
                    void Collect ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("_RevenueCat_Swift_3714", output);
        // Canonical should contain BOTH members.
        var canonicalBody = ExtractInterfaceBody(output, "RCAttribution");
        Assert.NotNull(canonicalBody);
        Assert.Contains("void Enable ()", canonicalBody);
        Assert.Contains("void Collect ()", canonicalBody);
    }

    /// <summary>
    /// Regression for the bug where two suffix interfaces targeting the same
    /// canonical caused the merge pass to issue two overlapping replace edits
    /// at the same offset. Applying them in sequence sliced into already-modified
    /// text, dropping members and corrupting comment prefixes (e.g. `//` → `/`).
    /// </summary>
    [Fact]
    public void Regression_Merge_MultipleSuffixesIntoSameCanonical()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCAttribution
                {
                    [Export ("enable")]
                    void Enable ();
                }

                [Category]
                [BaseType (typeof(RCAttribution))]
                interface RCAttribution_RevenueCat_Swift_3714
                {
                    // -(void)collect;
                    [Export ("collect")]
                    void Collect ();
                }

                [Category]
                [BaseType (typeof(RCAttribution))]
                interface RCAttribution_RevenueCat_Swift_4901
                {
                    // -(void)setEmail:(NSString *)email;
                    [Export ("setEmail:")]
                    void SetEmail (string email);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("_RevenueCat_Swift_", output);

        var body = ExtractInterfaceBody(output, "RCAttribution");
        Assert.NotNull(body);
        Assert.Contains("void Enable ()", body);
        Assert.Contains("void Collect ()", body);
        Assert.Contains("void SetEmail (string email)", body);

        // No `//` should have been mangled to `/` (regression).
        Assert.DoesNotMatch(@"^\s*/ -\(", output.ReplaceLineEndings("\n"));
    }

    /// <summary>
    /// Regression for the bug where merging dropped the leading whitespace
    /// before `{` and `}`, leaving braces at column 0 instead of the canonical's
    /// original indent.
    /// </summary>
    [Fact]
    public void Regression_Merge_PreservesBraceIndentation()
    {
        const string input = """
            namespace T
            {
            	[BaseType (typeof(NSObject))]
            	interface RCAttribution
            	{
            		[Export ("enable")]
            		void Enable ();
            	}

            	[Category]
            	[BaseType (typeof(RCAttribution))]
            	interface RCAttribution_RevenueCat_Swift_3714
            	{
            		[Export ("collect")]
            		void Collect ();
            	}
            }
            """;
        var output = ScriptRunner.Run(input);

        // After namespace dedent, the canonical's `{` and `}` should sit at
        // column 0 (the level they originally lived at, minus one for the
        // file-scoped-namespace conversion). The regression we're guarding
        // against is the merge stripping the indent of `{` while leaving the
        // `}` ALSO at column 0 — i.e., both braces should land at the SAME
        // column, paired with the interface declaration's column.
        var lines = output.ReplaceLineEndings("\n").Split('\n');
        var declIdx = Array.FindIndex(lines, l => l.Contains("interface RCAttribution") && !l.Contains("//"));
        Assert.True(declIdx >= 0, "interface declaration not found");
        // Brace lines: the very next line should be `{`, the matching `}` should
        // share its leading whitespace.
        var openLine = lines[declIdx + 1];
        Assert.Matches(@"^\s*\{\s*$", openLine);
        var openIndent = openLine[..(openLine.Length - openLine.TrimStart().Length)];
        // Find the closing `}` for this interface (paired by indentation).
        var closeIdx = Array.FindIndex(lines, declIdx + 1,
            l => l == openIndent + "}");
        Assert.True(closeIdx > declIdx, "matching close brace not found at same indent as open");
    }

    // ──────────────────────── Empty-interface removal ────────────────────

    [Fact]
    public void EmptyInterface_IsRemoved()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCEmpty
                {
                }

                [BaseType (typeof(NSObject))]
                interface RCNonEmpty
                {
                    [Export ("foo")]
                    void Foo ();
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("RCEmpty", output);
        Assert.Contains("RCNonEmpty", output);
    }

    /// <summary>
    /// Regression for the bug where empty marker interfaces (sharpie's
    /// forward-declaration-style `interface RCFoo { }`) got dropped even when
    /// other interfaces referenced `RCFoo` as a parameter or return type,
    /// producing CS0246 errors at build time.
    /// </summary>
    [Fact]
    public void Regression_EmptyInterface_IsKeptWhenReferencedElsewhere()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                [DisableDefaultCtor]
                interface RCPurchaseParams
                {
                }

                [BaseType (typeof(NSObject))]
                interface RCPurchases
                {
                    [Export ("purchaseWithParams:")]
                    void Purchase (RCPurchaseParams @params);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        // The forward-declared interface must remain even though it's empty.
        Assert.Contains("interface RCPurchaseParams", output);
        Assert.Contains("void Purchase (RCPurchaseParams", output);
    }

    // ──────────────────────── INativeObject for NSDictionary values ──────

    [Fact]
    public void DictionaryValueType_GainsINativeObject()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCValue
                {
                    [Export ("foo")]
                    string Foo { get; }
                }

                [BaseType (typeof(NSObject))]
                interface RCHolder
                {
                    [Export ("all", ArgumentSemantic.Copy)]
                    NSDictionary<NSString, RCValue> All { get; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.Matches(@"interface RCValue[^\n{]*:\s*INativeObject", output);
    }

    [Fact]
    public void ArrayElementType_GainsINativeObject()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCElement
                {
                    [Export ("foo")]
                    string Foo { get; }
                }

                [BaseType (typeof(NSObject))]
                interface RCHolder
                {
                    [Export ("items", ArgumentSemantic.Strong)]
                    NSArray<RCElement> Items { get; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.Matches(@"interface RCElement[^\n{]*:\s*INativeObject", output);
    }

    [Fact]
    public void DictionaryValueType_DoesNotDoubleAddINativeObject()
    {
        const string input = """
            namespace T
            {
                [BaseType (typeof(NSObject))]
                interface RCValue : INativeObject
                {
                    [Export ("foo")]
                    string Foo { get; }
                }

                [BaseType (typeof(NSObject))]
                interface RCHolder
                {
                    [Export ("all", ArgumentSemantic.Copy)]
                    NSDictionary<NSString, RCValue> All { get; }
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        // Should still inherit once, not "INativeObject, INativeObject".
        var count = Substrings.Count(output, "INativeObject");
        Assert.Equal(1, count);
    }

    // ──────────────────────── Unused delegate removal ────────────────────

    [Fact]
    public void UnusedTopLevelDelegate_IsRemoved()
    {
        const string input = """
            namespace T
            {
                delegate void UnusedHandler (NSError error);
                delegate void UsedHandler (NSError error);

                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Export ("doWith:")]
                    void DoWith ([BlockCallback] UsedHandler completion);
                }
            }
            """;
        var output = ScriptRunner.Run(input);
        Assert.DoesNotContain("UnusedHandler", output);
        Assert.Contains("UsedHandler", output);
    }

    // ──────────────────────── File-scoped namespace ──────────────────────

    [Fact]
    public void BlockNamespace_IsConvertedToFileScoped()
    {
        const string input = """
            using Foundation;

            namespace T
            {
            	[BaseType (typeof(NSObject))]
            	interface RCFoo
            	{
            		[Export ("bar")]
            		void Bar ();
            	}
            }
            """;
        var output = ScriptRunner.Run(input);
        // File-scoped: `namespace T;` and no closing `}` at end.
        Assert.Contains("namespace T;", output);
        Assert.DoesNotContain("namespace T\n{", output);
        Assert.DoesNotContain("namespace T\r\n{", output);
        // Interface should be at column 0 (dedented one level).
        Assert.Matches(@"^interface RCFoo", output.ReplaceLineEndings("\n").Split('\n')
            .First(l => l.Contains("interface RCFoo")));
    }

    // ──────────────────────── Idempotency ────────────────────────────────

    [Fact]
    public void Script_IsIdempotent()
    {
        const string input = """
            namespace T
            {
                [Obsoleted (PlatformName.iOS, 1, 0, message: "renamed")]
                [BaseType (typeof(NSObject))]
                interface RCOld
                {
                }

                [BaseType (typeof(NSObject))]
                interface RCFoo
                {
                    [Verify (MethodToProperty)]
                    [Obsoleted (PlatformName.iOS, 1, 0, message: "renamed")]
                    [Export ("oldBar")]
                    void OldBar ();

                    [Export ("newBar")]
                    void NewBar ();
                }
            }
            """;
        var once = ScriptRunner.Run(input);
        var twice = ScriptRunner.Run(once);
        Assert.Equal(once, twice);
    }

    // ──────────────────────── helpers ────────────────────────────────────

    /// <summary>
    /// Returns the inner body text of <c>interface NAME { ... }</c> in <paramref name="source"/>,
    /// or null if not found. Brace nesting one level deep is supported (for property
    /// accessor lists like <c>{ get; }</c>).
    /// </summary>
    private static string? ExtractInterfaceBody(string source, string name)
    {
        var marker = $"interface {name}";
        var idx = source.IndexOf(marker);
        if (idx < 0) return null;
        var brace = source.IndexOf('{', idx + marker.Length);
        if (brace < 0) return null;

        var depth = 1;
        for (var i = brace + 1; i < source.Length; i++)
        {
            if (source[i] == '{') depth++;
            else if (source[i] == '}')
            {
                depth--;
                if (depth == 0) return source[(brace + 1)..i];
            }
        }
        return null;
    }
}

internal static class Substrings
{
    public static int Count(string haystack, string needle)
    {
        if (needle.Length == 0) return 0;
        var count = 0;
        var i = 0;
        while ((i = haystack.IndexOf(needle, i, StringComparison.Ordinal)) >= 0)
        {
            count++;
            i += needle.Length;
        }
        return count;
    }
}
