name: Publish iOS
on: workflow_dispatch

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

  DOTNET_SDK_VERSION: 9.0.101
  BUILD_CONFIGURATION: Release

  #https://github.com/actions/runner-images/tree/main/images/macos
  #https://developer.apple.com/support/xcode/
  #https://xcodereleases.com/
  XCODE_VERSION: 16.2 #remove comment after 16.2 non-beta release: https://github.com/xamarin/xamarin-macios/issues/19157

  PROJECT_APP_PATH_FOLDER: src/Maui.RevenueCat.iOS
  PROJECT_PATH: src/Maui.RevenueCat.iOS/Maui.RevenueCat.iOS.csproj 

  ARTIFACT_FOLDER: ~/artifacts

jobs:
  build-ios:
    name: Build and publish iOS binary
    runs-on: macos-15
    steps:
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_${{env.XCODE_VERSION}}.app

      - uses: actions/checkout@v4

      - name: Create global.json to specify .NET version
        run: |
            echo '{"sdk":{"version":"${{ env.DOTNET_SDK_VERSION }}"}}' > ${{github.workspace}}/global.json

      - name: Setup .NET Core SDK ${{ env.DOTNET_SDK_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install MAUI iOS
        run: dotnet workload install ios maui-ios --ignore-failed-sources --version ${{ env.DOTNET_SDK_VERSION }}

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.PROJECT_PATH }} --ignore-failed-sources 

      - name: Build MAUI iOS
        run: > 
          dotnet build ${{ env.PROJECT_PATH }} 
          -c ${{ env.BUILD_CONFIGURATION }} 
          --no-restore

      - name: Pack NuGet Package
        run: >
          dotnet pack ${{ env.PROJECT_PATH }} 
          -o ${{env.ARTIFACT_FOLDER}} 
          --no-build
          --no-restore
          --include-symbols 
          --include-source

      - uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: |
            ${{env.ARTIFACT_FOLDER}}/*.nupkg
            ${{env.ARTIFACT_FOLDER}}/*.snupkg

      - name: Publish Nuget
        run: >
          dotnet nuget push ${{env.ARTIFACT_FOLDER}}/*.nupkg 
          --api-key ${{ secrets.NUGET_API_KEY }} 
          --source https://api.nuget.org/v3/index.json